title: Alexander Moreira de Morais
tagline: Website pessoal
lang: pt-BR
charset: UTF-8

theme: jekyll-theme-midnight
plugins:
  - jekyll-feed

sass:
  style: compressed

#include:
#  - _includes/head-custom.html
